export const CONFIG = {
  STARTING_GEM_FACTOR: 130,
  
  CLICKER_INITIAL_COST: 10,
  PICKAXE_INITIAL_COST: 130,
  DRILL_INITIAL_COST: 500,

  CLICKER_INCREASE_FACTOR: 1,
  PICKAXE_INCREASE_FACTOR: 4,
  DRILL_INCREASE_FACTOR: 12,

  COST_GROWTH_FACTOR: 1.3,
  AUTO_TICK_INTERVAL: 250,

  AUTO_GEM_TOOLS: ['pickaxe', 'drill']
};
